[project]
name = "ByteGaurd"
version = "0.1.0"
description = "A script to monitor download activity for a specified process and shut down if no significant activity is detected for a set period of time."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "psutil>=7.0.0",
]
